### PR TITLE
Added Boss, Skill Points, and fixed some minor text

### PR DESCRIPTION
**Pull request by KingofKFCJamal**
Added some things and fixed some things. Planning on adding other types of monsters later.

### CODE REVIEW

**Comment by quizque** [comment]
I'll check it out tomorrow and some things might need to change but that won't be until the story gets added. I'll also need to reorganize the files for the boss and other enemies. The "Gaben boss" might become an Easter egg/rare boss but I would like to thank you for your work. I'm currently stuck doing exams so it is hard for me to work on my projects.

Just an FYI, you can also update the README.md with your new commands or I can do it for you later.

**Comment by quizque** [comment]
Also just a tip, try to comment your code. We are all guilty of this and I'll comment it more once exams are over but it will be better for people who just saw this project to understand it.

**Review by quizque — CHANGES_REQUESTED** [review]
Looking good but try to use string.Format instead of "stuff" + some var + "more stuff"

**Review by quizque — APPROVED** [review]

**Comment by quizque** [comment]
Sorry, pressed wrong button but if you can, try to change them.

**Comment by KingofKFCJamal** [comment]
Alright

**Pull request merged**
